services:
  frontend:
    depends_on:
      - backend
    image: "kinggrey/voting-application-frontend:latest"
    environment:
      - "NEXT_PUBLIC_API_URL=https://backend.13.61.25.120.sslip.io"
      - NEXT_PUBLIC_WS_URL=websocket.13.61.25.120.sslip.io
      - NODE_ENV=production

  backend:
    image: "kinggrey/voting-application-backend:latest"
    environment:
      - "FRONTEND_URL=https://frontend.13.61.25.120.sslip.io"
      - RP_ID=frontend.13.61.25.120.sslip.io
      - "RP_ORIGIN=https://frontend.13.61.25.120.sslip.io"
      - RUST_BACKTRACE=1
