services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./polling-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://voting-application-s45r.onrender.com
        - NEXT_PUBLIC_WS_URL=voting-application-s45r.onrender.com
    ports:
      - 3002:3002
    environment:
      - NEXT_PUBLIC_API_URL=https://voting-application-s45r.onrender.com
      - NEXT_PUBLIC_WS_URL=voting-application-s45r.onrender.com

  backend:
    build:
      context: ./polling-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 3003:3003
    environment:
      - FRONTEND_URL=https://voting-application-seven.vercel.app
      - RP_ID=voting-application-seven.vercel.app
      - RP_ORIGIN=https://voting-application-seven.vercel.app
