services:
  frontend:
    depends_on:
      - backend
    image: kinggrey/voting-application-frontend:latest
    ports:
      - 3002:3002
    environment:
      - NEXT_PUBLIC_API_URL=http://16.171.137.206:3000
      - NEXT_PUBLIC_WS_URL=16.171.137.206:3003
      - NODE_ENV=production

  backend:
    image: kinggrey/voting-application-backend:latest
    ports:
      - 3000:3000
      - 3003:3003
    environment:
      - FRONTEND_URL=http://16.171.137.206:3002
      - RP_ID=16.171.137.206
      - RP_ORIGIN=http://16.171.137.206:3002
