version: "3.8"

services:
  frontend:
    depends_on:
      - backend

    build:
      context: ./polling-frontend
      dockerfile: Dockerfile

    ports:
      - 3002:3002

    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_WS_URL=ws://localhost:3003

  backend:
    build:
      context: ./polling-backend
      dockerfile: Dockerfile

    ports:
      - 3000:3000
      - 3003:3003

    environment:
      - FRONTEND_URL=http://localhost:3000
      - RP_ID=localhost
      - RP_ORIGIN=http://localhost:3001
