name: Build And Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log files
        run: ls -al

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: polling-frontend/yarn.lock

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: cargo fmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  dependencies:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4

      - name: Log files
        run: ls -al

      - name: Install frontend Dependencies
        working-directory: ./polling-frontend
        run: yarn install

      - name: Build frontend
        working-directory: ./polling-frontend
        env:
          NEXT_PUBLIC_API_URL: https://voting-application-s45r.onrender.com
          NEXT_PUBLIC_WS_URL: voting-application-s45r.onrender.com
        run: yarn build

      - name: Build Backend
        working-directory: ./polling-backend
        run: cargo build --release --verbose

  deploy:
    needs: [setup, dependencies]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
